site_name: "PomdAPI"
repo_name: "jimixxperez/pomdapi"
repo_url: "https://github.com/jimixxperez/pomdapi"

theme:
  name: material
  logo: /home/jeremy/Downloads/
  palette:
    scheme: default
    primary: "#E63946"       # Pomegranate Red
    accent: "#A8DADC"        # Soft Teal
  # Advanced color overrides
  # NOTE: this requires mkdocs-material advanced color support
  # see https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors
  features:
    - content.code.copy
  custom_colors:
    primary: "#E63946"
    accent: "#A8DADC"
    scheme:
      background: "#F9FAFB"
      surface: "#F5F7F8"
      on_surface: "#2D2D2D"
      on_background: "#2D2D2D"


extra_css:
  - css/papperlapi_custom.css

markdown_extensions:
- admonition
- tables
- admonition
- attr_list
- md_in_html
- toc:
    permalink: true
- pymdownx.highlight:
    use_pygments: true
    anchor_linenums: true
    line_spans: __span
    pygments_style: monokai
- pymdownx.details
- pymdownx.caret
- pymdownx.critic
- pymdownx.mark
- pymdownx.superfences
- pymdownx.snippets
- pymdownx.tilde
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          # By default, mkdocstrings will look for Python files in your project.
          # If your source code is in a subdirectory, you can specify that path here.
          paths: ["./src"]
          # You can also use these lines to ensure your modules are importable
          # setup_commands:
          #   - import sys
          #   - sys.path.append(".")
#   

nav:
  - Introduction: index.md
  - getting-started.md
  - hands-on-overview.md
  - Documentation:
    - api.md
  - API Reference:
      - Core:
          - API: references/core_api.md
          - Caching: references/core_caching.md
          - Types: references/core_types.md
          - RW Lock: references/core_rw_lock.md
      - API Modules:
          - HTTP: references/api_http.md
          - JSON RPC: references/api_jsonrpc.md
          - XML RPC: references/api_xmlrpc.md
      - Cache Backends:
          - In-Memory Cache: references/cache_in_memory.md
          - Memcached Cache: references/cache_memcached.md
          - Redis Cache: references/cache_redis.md
      - Examples:
          - HTTP + GitHub: references/examples_http_github.md
          - JSONRPC + Ethereum: references/examples_jsonrpc_eth.md
  - About: about.md

