site_name: "papperlapi"
repo_url: "https://github.com/YourGitHubUserName/papperlapi"

theme:
  name: material
  highlightjs: true

extra_css:
  - css/papperlapi_custom.css

markdown_extensions:
- admonition
- toc:
    permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          # By default, mkdocstrings will look for Python files in your project.
          # If your source code is in a subdirectory, you can specify that path here.
          paths: ["."]
          # You can also use these lines to ensure your modules are importable
          # setup_commands:
          #   - import sys
          #   - sys.path.append(".")
#   

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Python API Reference:
      - Core:
          - API: references/core_api.md
          - Caching: references/core_caching.md
          - Types: references/core_types.md
          - RW Lock: references/core_rw_lock.md
      - API Modules:
          - HTTP: references/api_http.md
          - JSON RPC: references/api_jsonrpc.md
          - XML RPC: references/api_xmlrpc.md
      - Cache Backends:
          - In-Memory Cache: references/cache_in_memory.md
          - Memcached Cache: references/cache_memcached.md
          - Redis Cache: references/cache_redis.md
      - Examples:
          - HTTP + GitHub: references/examples_http_github.md
          - JSONRPC + Ethereum: references/examples_jsonrpc_eth.md
  - About: about.md

